kind: Service
apiVersion: v1

metadata:
  name: db
  labels:
    name: db-service
    app: demo-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgress-app-pod
    app: demo-app
