apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgress-deployment
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: postgress-app-pod
      app: demo-app
  template:
    metadata:
      name: postgress-app-pod
      labels:
        name: postgress-app-pod
        app: demo-app
    spec:
      containers:
        - name: postgress-app
          image: postgres:9.4
          ports:
            - containerPort: 5432