apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
  labels:
    app: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      name: redis-app-pod
      app: demo-app
  template:
    metadata:
      name: redis-app-pod
      labels:
        name: redis-app-pod
        app: demo-app
    spec:
      containers:
        - name: redis-app
          image: redis
          ports:
            - containerPort: 6379
